import { NextRequest, NextResponse } from 'next/server';
import { createClient, createServiceClient } from '@/lib/supabase/server';
import { buildConformanceTable, ConformanceLevel } from '@/lib/vpat/conformance';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

async function getVpatWithTable(db: ReturnType<typeof createServiceClient>, id: string, userId: string) {
  const { data: vpat } = await db
    .from('vpat_reports')
    .select('*, scans(url, compliance_score, wcag_version)')
    .eq('id', id)
    .eq('user_id', userId)
    .single();

  if (!vpat) return null;

  const { data: violations } = await db
    .from('violations')
    .select('rule_id, impact, fix_summary, node_count, tags')
    .eq('scan_id', vpat.scan_id);

  const baseTable = buildConformanceTable(
    (violations || []).map((v: any) => ({
      id: v.rule_id,
      impact: v.impact,
      help: v.fix_summary,
      node_count: v.node_count || 1,
      tags: v.tags,
    }))
  );

  // Merge in any manual overrides the agency has saved
  const overrides = (vpat.criterion_overrides || {}) as Record<string, { level: ConformanceLevel; remarks: string }>;
  const table = baseTable.map((row) => {
    const override = overrides[row.criterion.number];
    if (override) {
      return { ...row, level: override.level, remarks: override.remarks, autoGenerated: false };
    }
    return row;
  });

  return { vpat, table };
}

export async function GET(request: NextRequest, { params }: { params: { id: string } }) {
  const authClient = await createClient();
  const db = createServiceClient();

  const { data: { user } } = await authClient.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Sign in required' }, { status: 401 });

  const result = await getVpatWithTable(db, params.id, user.id);
  if (!result) return NextResponse.json({ error: 'VPAT report not found' }, { status: 404 });

  return NextResponse.json({
    ...result.vpat,
    table: result.table,
  }, {
    headers: { 'Cache-Control': 'no-store, no-cache, must-revalidate' },
  });
}

const updateSchema = z.object({
  product_name: z.string().min(1).max(200).optional(),
  product_version: z.string().max(50).optional(),
  product_description: z.string().max(1000).optional(),
  evaluator_name: z.string().min(1).max(200).optional(),
  evaluator_contact: z.string().max(200).optional(),
  evaluation_methods: z.string().max(2000).optional(),
  status: z.enum(['draft', 'finalized']).optional(),
  criterion_override: z.object({
    number: z.string(),
    level: z.enum(['Supports', 'Partially Supports', 'Does Not Support', 'Not Evaluated']),
    remarks: z.string().max(1000),
  }).optional(),
});

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const authClient = await createClient();
  const db = createServiceClient();

  const { data: { user } } = await authClient.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Sign in required' }, { status: 401 });

  const body = await request.json();
  const parsed = updateSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: 'Invalid request', details: parsed.error.flatten() }, { status: 400 });
  }

  const { criterion_override, ...fields } = parsed.data;

  const { data: existing } = await db
    .from('vpat_reports')
    .select('criterion_overrides')
    .eq('id', params.id)
    .eq('user_id', user.id)
    .single();

  if (!existing) return NextResponse.json({ error: 'VPAT report not found' }, { status: 404 });

  const updatePayload: Record<string, any> = { ...fields, updated_at: new Date().toISOString() };

  if (criterion_override) {
    const overrides = { ...(existing.criterion_overrides || {}) };
    overrides[criterion_override.number] = {
      level: criterion_override.level,
      remarks: criterion_override.remarks,
    };
    updatePayload.criterion_overrides = overrides;
  }

  if (fields.status === 'finalized') {
    updatePayload.finalized_at = new Date().toISOString();
  }

  const { error } = await db
    .from('vpat_reports')
    .update(updatePayload)
    .eq('id', params.id)
    .eq('user_id', user.id);

  if (error) {
    console.error('Failed to update VPAT report:', error);
    return NextResponse.json({ error: 'Failed to update' }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

export async function DELETE(request: NextRequest, { params }: { params: { id: string } }) {
  const authClient = await createClient();
  const db = createServiceClient();

  const { data: { user } } = await authClient.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Sign in required' }, { status: 401 });

  await db.from('vpat_reports').delete().eq('id', params.id).eq('user_id', user.id);
  return NextResponse.json({ success: true });
}