import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { escapeHtml } from '@/lib/escapeHtml'

// Step 2: any paid tier (starter/growth/enterprise) unlocks upgraded statement generator.
const PLAN_GATE = ['starter', 'growth', 'enterprise'] as const

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  const cookieStore = cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll() },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieStore.set(name, value, options)
          )
        },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new Response('Unauthorized', { status: 401 })

  const { data: profile } = await supabase
    .from('profiles')
    .select('subscription_status, full_name')
    .eq('id', user.id)
    .single()

  if (!PLAN_GATE.includes(profile?.subscription_status || 'free')) {
    return Response.json(
      { error: 'Accessibility Statement requires a Starter plan or higher' },
      { status: 403 }
    )
  }

  const { data: report } = await supabase
    .from('reports')
    .select('*, scans(*)')
    .eq('id', params.id)
    .eq('user_id', user.id)
    .single()

  if (!report) return new Response('Not found', { status: 404 })

  const scan = report.scans as any

  const { data: violations } = await supabase
    .from('violations')
    .select('rule_description')
    .eq('scan_id', report.scan_id)

  // Extract distinct categories from violation rule_descriptions
  const categories = new Set<string>()
  if (violations) {
    for (const v of violations) {
      if (v.rule_description) {
        // Extract meaningful keywords from description
        const desc = v.rule_description.toLowerCase()
        if (desc.includes('color contrast') || desc.includes('contrast')) categories.add('color contrast')
        if (desc.includes('alt text') || desc.includes('alternative text') || desc.includes('image')) categories.add('image alt text')
        if (desc.includes('form') && (desc.includes('label') || desc.includes('input'))) categories.add('form labels')
        if (desc.includes('link name') || desc.includes('link text') || desc.includes('anchor')) categories.add('link names')
        if (desc.includes('button name') || desc.includes('button text')) categories.add('button names')
        if (desc.includes('document language') || desc.includes('lang')) categories.add('document language')
        if (desc.includes('aria')) categories.add('ARIA attributes')
        if (desc.includes('heading') || desc.includes('h1') || desc.includes('headings')) categories.add('heading structure')
        if (desc.includes('landmark') || desc.includes('region')) categories.add('landmark regions')
        if (desc.includes('list')) categories.add('list structure')
        if (desc.includes('focus') || desc.includes('keyboard')) categories.add('keyboard/focus navigation')
        if (desc.includes('role')) categories.add('ARIA roles')
        if (categories.size === 0) categories.add('WCAG 2.1 Level AA compliance')
      }
    }
  }

  const categoriesList = categories.size > 0
    ? Array.from(categories).slice(0, 8).join(', ')
    : 'WCAG 2.1 Level AA compliance'

  const today = new Date()
  const todayStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const nextReview = new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000)
  const nextReviewStr = nextReview.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const scanDate = new Date(report.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const remainingIssues = scan.total_violations > 0
    ? `We have identified ${scan.total_violations} remaining issue${scan.total_violations > 1 ? 's' : ''} through automated testing, which our team is actively working to resolve.`
    : 'Our most recent automated scan found no outstanding issues.'

  const statementHtml = `<!-- Accessibility Statement — Generated by WCAG Scanner on ${todayStr} -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Accessibility Statement — ${escapeHtml(scan.url)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #f8f9fa; padding: 40px 20px; }
    .container { max-width: 720px; margin: 0 auto; background: #fff; border-radius: 12px; padding: 48px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
    h2 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    h3 { font-size: 18px; font-weight: 600; margin: 28px 0 10px; }
    p { font-size: 15px; line-height: 1.7; color: #374151; margin-bottom: 14px; }
    ul { margin: 0 0 14px 20px; }
    li { font-size: 15px; line-height: 1.7; color: #374151; }
    strong { color: #111827; }
    .meta { font-size: 13px; color: #6b7280; margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb; }
    .score-badge { display: inline-block; background: #f3f4f6; padding: 4px 12px; border-radius: 6px; font-weight: 600; font-size: 14px; }
    .regulatory-section { margin: 28px 0 10px; }
    .regulatory-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; margin: 14px 0; }
    .reg-badge { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; background: #f9fafb; }
    .reg-badge strong { display: block; font-size: 15px; color: #111827; }
    .reg-badge span { display: block; font-size: 12px; color: #6b7280; margin-top: 4px; }
    .reg-disclaimer { font-size: 12px; color: #6b7280; margin-top: 10px; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="container">
    <h2>Accessibility Statement</h2>
    <p>We are committed to ensuring digital accessibility for people of all abilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards.</p>

    <h3>Scope of This Statement</h3>
    <p>This accessibility statement applies to <strong>${escapeHtml(scan.url)}</strong>, which was evaluated through automated conformance testing. This statement reflects the results of an automated scan and is updated as new scans are completed.</p>

    <h3>Conformance Status</h3>
    <p>The Web Content Accessibility Guidelines (WCAG) define requirements for designers and developers to improve accessibility for people with disabilities. Our website has been evaluated against WCAG 2.1 Level AA using automated testing tools, including axe-core.</p>
    <p>As of <strong>${todayStr}</strong>, our site achieved an automated compliance score of <strong>${scan.compliance_score}/100</strong>. ${remainingIssues}</p>

    <h3>Specific Areas Identified for Improvement</h3>
    <p>Based on our most recent automated scan, the following areas have been identified that may require attention: <strong>${categoriesList}</strong>. Our team is actively working to address these issues in order of severity.</p>

    <h3>Technical Specifications</h3>
    <p>This statement is based on conformance testing using <strong>axe-core (Deque Systems)</strong>, evaluating <strong>WCAG 2.1 Level AA</strong> success criteria across the Perceivable, Operable, Understandable, and Robust (POUR) principles. Automated testing covers approximately 57% of WCAG success criteria; the remaining 43% require manual evaluation.</p>

    <h3>Measures We Take</h3>
    <ul>
      <li>Regular automated accessibility scanning of our website</li>
      <li>Ongoing monitoring for newly introduced accessibility issues</li>
      <li>Prompt remediation of identified issues based on severity</li>
      <li>Use of industry-standard testing tools (axe-core) for consistent, reliable results</li>
    </ul>

    <h3>Feedback</h3>
    <p>We welcome your feedback on the accessibility of our website. Please let us know if you encounter accessibility barriers by contacting us at <strong>reports@wcagscannerr.com</strong>.</p>

    <h3>Limitations</h3>
    <p>Despite our best efforts, automated testing tools detect approximately 57% of WCAG success criteria. Some issues may only be identified through manual testing. We are committed to identifying and fixing any remaining barriers as they are discovered.</p>

    <h3>Regulatory Coverage</h3>
    <div class="regulatory-section">
      <div class="regulatory-grid">
        <div class="reg-badge"><strong>ADA</strong> (United States)<span>References WCAG 2.1 AA</span></div>
        <div class="reg-badge"><strong>California Unruh Act</strong> (United States)<span>References WCAG 2.1 AA</span></div>
        <div class="reg-badge"><strong>Section 508</strong> (US Federal)<span>References WCAG 2.0 AA</span></div>
        <div class="reg-badge"><strong>UK Equality Act 2010</strong> (United Kingdom)<span>References WCAG 2.1 AA</span></div>
        <div class="reg-badge"><strong>EN 301 549 / EAA</strong> (European Union)<span>References WCAG 2.1 AA</span></div>
        <div class="reg-badge"><strong>Australian DDA</strong> (Australia)<span>References WCAG 2.0/2.1 AA</span></div>
        <div class="reg-badge"><strong>Canada ACA / AODA</strong> (Canada)<span>References WCAG 2.0 AA</span></div>
      </div>
      <p class="reg-disclaimer">
        This automated scan tests against the WCAG 2.1 AA standard, which is the technical baseline referenced by all regulations listed above. This does not guarantee legal compliance with any specific regulation — consult a qualified attorney in the relevant jurisdiction for legal certainty.
      </p>
    </div>

    <h3>Review Cycle</h3>
    <p>This accessibility statement is reviewed and updated following each automated scan. Last scan: <strong>${scanDate}</strong>. Next scheduled review: <strong>${nextReviewStr}</strong>.</p>

    <p><em>This statement was last reviewed on ${todayStr} based on automated scan data and is updated as new scans are completed.</em></p>

    <p class="meta">Generated by WCAG Scanner — This statement reflects automated scan results and is not legal advice.</p>
  </div>
</body>
</html>`

  return new Response(statementHtml, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="accessibility-statement-${params.id}.html"`,
    },
  })
}