'use client'

import { useEffect, useState, useCallback } from 'react'
import Link from 'next/link'
import { ArrowLeft, Download, Loader2, Pencil, Check, X, Lock, CheckCircle2 } from 'lucide-react'

interface ConformanceRow {
  criterion: { number: string; name: string; level: string; principle: string }
  level: 'Supports' | 'Partially Supports' | 'Does Not Support' | 'Not Evaluated'
  remarks: string
  autoGenerated: boolean
}

interface VpatData {
  id: string
  product_name: string
  product_version: string | null
  evaluator_name: string
  evaluator_contact: string | null
  evaluation_methods: string
  standard: string
  status: 'draft' | 'finalized'
  acr_pdf_url?: string | null
  scans: { url: string; compliance_score: number }
  table: ConformanceRow[]
}

const LEVELS: ConformanceRow['level'][] = ['Supports', 'Partially Supports', 'Does Not Support', 'Not Evaluated']

const levelColor: Record<string, string> = {
  'Supports': '#16A34A',
  'Partially Supports': '#D97706',
  'Does Not Support': '#DC2626',
  'Not Evaluated': '#6B7280',
}

export default function VpatEditorPage({ params }: { params: { id: string } }) {
  const [data, setData] = useState<VpatData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [editingRow, setEditingRow] = useState<string | null>(null)
  const [draftLevel, setDraftLevel] = useState<ConformanceRow['level']>('Supports')
  const [draftRemarks, setDraftRemarks] = useState('')
  const [saving, setSaving] = useState(false)
  const [finalizing, setFinalizing] = useState(false)

  const fetchData = useCallback(async () => {
    try {
      const res = await fetch(`/api/vpat/${params.id}`)
      const json = await res.json()
      if (!res.ok) throw new Error(json.error || 'Failed to load VPAT')
      setData(json)
    } catch (err: any) {
      setError(err.message)
    }
  }, [params.id])

  useEffect(() => { fetchData() }, [fetchData])

  const startEdit = (row: ConformanceRow) => {
    setEditingRow(row.criterion.number)
    setDraftLevel(row.level)
    setDraftRemarks(row.remarks)
  }

  const saveEdit = async (criterionNumber: string) => {
    setSaving(true)
    try {
      const res = await fetch(`/api/vpat/${params.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          criterion_override: { number: criterionNumber, level: draftLevel, remarks: draftRemarks },
        }),
      })
      if (!res.ok) throw new Error('Failed to save')
      setEditingRow(null)
      await fetchData()
    } catch (err: any) {
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  const finalize = async () => {
    if (!confirm('Finalize this VPAT? This will generate the ACR (Accessibility Conformance Report) PDF and mark it as a final report.')) return
    setFinalizing(true)
    try {
      const res = await fetch(`/api/vpat/${params.id}/finalize`, { method: 'POST' })
      if (!res.ok) throw new Error('Failed to finalize')
      await fetchData()
    } catch (err: any) {
      setError(err.message)
    } finally {
      setFinalizing(false)
    }
  }

  if (error) {
    return (
      <div className="p-6 max-w-3xl mx-auto text-center py-20">
        <p className="text-red-400">{error}</p>
        <Link href="/reports" className="text-sm text-accent hover:underline mt-3 inline-block">Back to Reports</Link>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="p-6 flex items-center justify-center py-20">
        <Loader2 className="w-6 h-6 animate-spin text-text-muted" />
      </div>
    )
  }

  const principles = ['Perceivable', 'Operable', 'Understandable', 'Robust']
  const summary = data.table.reduce((acc, r) => { acc[r.level] = (acc[r.level] || 0) + 1; return acc }, {} as Record<string, number>)

  return (
    <div className="p-6 max-w-5xl mx-auto pb-20">
      <Link href="/reports" className="inline-flex items-center gap-2 text-sm text-text-secondary hover:text-text-primary mb-6">
        <ArrowLeft className="w-4 h-4" /> Back to Reports
      </Link>

      <div className="flex items-start justify-between flex-wrap gap-4 mb-6">
        <div>
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-bold text-text-primary">{data.product_name}</h1>
            <span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${data.status === 'finalized' ? 'bg-emerald-500/15 text-emerald-400' : 'bg-amber-500/15 text-amber-400'}`}>
              {data.status === 'finalized' ? 'Final' : 'Draft'}
            </span>
          </div>
          <p className="text-sm text-text-secondary mt-1">
            {data.scans?.url} · Evaluated by {data.evaluator_name} · {data.standard}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {data.status !== 'finalized' && (
            <button
              onClick={finalize}
              disabled={finalizing}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-surface-elevated border border-border text-text-primary hover:bg-border transition-colors"
            >
              {finalizing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
              Finalize
            </button>
          )}
          {/*
            On mobile, finalizing already produces the ACR PDF and users
            end up triggering a save/download from that flow — a second,
            separate "Download" button here just duplicates that action
            and confuses the tap target. We keep it for tablet/desktop
            (sm: and up), where there's room for both actions to coexist
            without ambiguity, and where someone may want to re-download
            a report they finalized in an earlier session.
          */}
          {data.acr_pdf_url ? (
            <a
              href={data.acr_pdf_url}
              target="_blank"
              rel="noopener noreferrer"
              className="hidden sm:flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-emerald-600 text-white hover:opacity-90 transition-colors"
            >
              <Download className="w-4 h-4" /> Download ACR (PDF)
            </a>
          ) : (
            <a
              href={`/api/vpat/${params.id}/pdf`}
              className="hidden sm:flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-accent text-white hover:opacity-90 transition-colors"
            >
              <Download className="w-4 h-4" /> Download PDF
            </a>
          )}
        </div>
      </div>

      {/* Summary chips */}
      <div className="flex flex-wrap gap-3 mb-8">
        {LEVELS.map((level) => (
          <div key={level} className="px-4 py-2.5 rounded-xl border border-border bg-card">
            <p className="text-2xl font-bold" style={{ color: levelColor[level] }}>{summary[level] || 0}</p>
            <p className="text-xs text-text-muted mt-0.5">{level}</p>
          </div>
        ))}
      </div>

      <p className="text-sm text-text-secondary mb-6 flex items-start gap-2">
        <Pencil className="w-4 h-4 shrink-0 mt-0.5" />
        Every row below was auto-generated from this scan's results. Click any row to review and override it — especially rows marked
        "Not Evaluated," which need manual testing before you can honestly report them as Supports.
      </p>

      {/* Conformance table by principle */}
      <div className="space-y-8">
        {principles.map((principle) => {
          const rows = data.table.filter((r) => r.criterion.principle === principle)
          return (
            <div key={principle}>
              <h2 className="text-sm font-semibold text-text-muted uppercase tracking-wider mb-3">{principle}</h2>
              <div className="border border-border rounded-xl overflow-hidden divide-y divide-border">
                {rows.map((row) => {
                  const isEditing = editingRow === row.criterion.number
                  return (
                    <div key={row.criterion.number} className="p-4 bg-card">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium text-text-primary">
                            <span className="text-text-muted font-mono mr-2">{row.criterion.number}</span>
                            {row.criterion.name}
                            <span className="ml-2 text-xs text-text-muted">Level {row.criterion.level}</span>
                          </p>

                          {!isEditing && (
                            <>
                              <span
                                className="inline-block mt-2 px-2 py-0.5 rounded text-xs font-semibold"
                                style={{ backgroundColor: levelColor[row.level] + '1a', color: levelColor[row.level] }}
                              >
                                {row.level}
                              </span>
                              <p className="text-sm text-text-secondary mt-1.5">{row.remarks}</p>
                              {!row.autoGenerated && (
                                <p className="text-xs text-accent mt-1">Manually edited</p>
                              )}
                            </>
                          )}

                          {isEditing && (
                            <div className="mt-3 space-y-2">
                              <select
                                value={draftLevel}
                                onChange={(e) => setDraftLevel(e.target.value as ConformanceRow['level'])}
                                className="px-2 py-1.5 bg-surface-elevated border border-border rounded-lg text-sm text-text-primary"
                              >
                                {LEVELS.map((l) => <option key={l} value={l}>{l}</option>)}
                              </select>
                              <textarea
                                value={draftRemarks}
                                onChange={(e) => setDraftRemarks(e.target.value)}
                                rows={3}
                                className="w-full px-3 py-2 bg-surface-elevated border border-border rounded-lg text-sm text-text-primary outline-none focus:border-accent"
                              />
                              <div className="flex gap-2">
                                <button
                                  onClick={() => saveEdit(row.criterion.number)}
                                  disabled={saving}
                                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-accent text-white"
                                >
                                  {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" />}
                                  Save
                                </button>
                                <button
                                  onClick={() => setEditingRow(null)}
                                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-surface-elevated border border-border text-text-secondary"
                                >
                                  <X className="w-3.5 h-3.5" /> Cancel
                                </button>
                              </div>
                            </div>
                          )}
                        </div>

                        {!isEditing && (
                          <button
                            onClick={() => startEdit(row)}
                            className="shrink-0 p-2 rounded-lg text-text-muted hover:text-text-primary hover:bg-surface-elevated transition-colors"
                            aria-label={`Edit ${row.criterion.number}`}
                          >
                            <Pencil className="w-4 h-4" />
                          </button>
                        )}
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )
        })}
      </div>

      {data.status === 'finalized' && (
        <div className="flex items-center gap-2 text-emerald-400 text-sm mt-8">
          <CheckCircle2 className="w-4 h-4" /> This VPAT has been finalized.
        </div>
      )}
    </div>
  )
}