import { WCAG_21_CRITERIA, WcagCriterion } from './wcagCriteria'

export type ConformanceLevel = 'Supports' | 'Partially Supports' | 'Does Not Support' | 'Not Evaluated'

export interface ConformanceRow {
  criterion: WcagCriterion
  level: ConformanceLevel
  remarks: string
  /** Whether this row's remarks were auto-generated or manually edited
   * by the agency before finalizing — surfaced in the editor UI so it's
   * clear which rows still need a human look. */
  autoGenerated: boolean
}

interface ViolationLite {
  id: string
  impact: string
  help: string
  node_count: number
  tags: string[] | null
}

/**
 * Builds a full VPAT conformance table from a scan's violations.
 *
 * Methodology (this exact logic should also appear in the generated
 * document's "Evaluation Methods" section, since a client relying on
 * this as a compliance record deserves to know how each row was decided):
 *   - If any violation's axe tags match this criterion -> real finding
 *     exists. "Does Not Support" if any matching violation is critical/
 *     serious impact, otherwise "Partially Supports".
 *   - Else if the criterion is automatable and no matching violation was
 *     found -> "Supports" (automated testing found no issues).
 *   - Else (criterion isn't automatable by axe-core) -> "Not Evaluated",
 *     regardless of scan results, since it was never actually tested.
 */
export function buildConformanceTable(violations: ViolationLite[]): ConformanceRow[] {
  return WCAG_21_CRITERIA.map((criterion) => {
    const matching = violations.filter((v) => (v.tags || []).includes(criterion.axeTag))

    if (matching.length > 0) {
      const hasSevere = matching.some((v) => v.impact === 'critical' || v.impact === 'serious')
      const totalInstances = matching.reduce((sum, v) => sum + (v.node_count || 1), 0)
      const ruleNames = matching.map((v) => v.help).slice(0, 3).join('; ')

      return {
        criterion,
        level: hasSevere ? 'Does Not Support' : 'Partially Supports',
        remarks: `Automated testing identified ${totalInstances} instance${totalInstances === 1 ? '' : 's'} affecting this criterion (${ruleNames}${matching.length > 3 ? ', and other issues' : ''}).`,
        autoGenerated: true,
      }
    }

    if (criterion.automatable) {
      return {
        criterion,
        level: 'Supports' as ConformanceLevel,
        remarks: 'No issues identified through automated testing against this criterion.',
        autoGenerated: true,
      }
    }

    return {
      criterion,
      level: 'Not Evaluated' as ConformanceLevel,
      remarks: 'This criterion requires manual evaluation and was not covered by automated testing.',
      autoGenerated: true,
    }
  })
}

export function summarizeConformance(rows: ConformanceRow[]) {
  const counts = { 'Supports': 0, 'Partially Supports': 0, 'Does Not Support': 0, 'Not Evaluated': 0 }
  for (const row of rows) counts[row.level]++
  return counts
}